import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Link from "next/link";
import { gql } from "@apollo/client";
import { getApolloClient } from "../lib/apollo-client";
import React, { useState } from "react";
import FormValidation from '@/components/Form';

const inter = Inter({ subsets: ['latin'] })

export default function Home({ page, posts }) {
  const { title, description } = page;
  const [selectedCategory, setSelectedCategory] = useState("Any");
  const filteredPosts = selectedCategory === "Any" ? posts : posts.filter(post => post.categories.edges[0].node.name === selectedCategory);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <form>
          <label>
            Select Movie Genre:
            <select
              value={selectedCategory}
              onChange={(event) => setSelectedCategory(event.target.value)}
            >
              <option value="Any">Any</option>
              {posts && posts.length > 0 && (
                <>
                  {posts.map((post) => (
                    post.categories.edges.map((category) => (
                      <option key={category.node.name} value={category.node.name}>
                        {category.node.name}
                      </option>
                    ))
                  ))}
                </>
              )}
            </select>
          </label>
        </form>
        <ul className="">
          {filteredPosts &&
            filteredPosts.length > 0 &&
            filteredPosts.map((post) => {
              return (
                <li key={post.slug} className="">
                  <Link href={post.path}>
                    <Image src={post.featuredImage.node.sourceUrl} alt={post.title} width={1920} height={1080} />
                    <h3
                      dangerouslySetInnerHTML={{
                        __html: post.title,
                      }}
                    />
                    <div
                      className=""
                      dangerouslySetInnerHTML={{
                        __html: post.excerpt,
                      }}
                    />
                    <div>{post.categories.edges[0].node.name}</div>
                  </Link>
                </li>
              );
            })}

            {!filteredPosts ||
            (filteredPosts.length === 0 && (
              <li>
                <p>Oops, no posts found!</p>
              </li>
            ))}
        </ul>
        <FormValidation />
      </main>
    </>
  )
}

export async function getStaticProps({ locale }) {
  const apolloClient = getApolloClient();

  const language = locale.toUpperCase();

  const data = await apolloClient.query({
    query: gql`
      query posts($language: LanguageCodeFilterEnum!, $selectedCategory: String!) {
        posts(where: { language: $language, categoryName: $selectedCategory }, first:2) {
          edges {
            node {
              id
              excerpt
              title
              slug
              featuredImage {
                node {
                  sourceUrl
                }
              }
              categories {
                edges {
                  node {
                    name
                  }
                }
              }
              language {
                code
                locale
              }
            }
          }
        }
        generalSettings {
          title
          description
        }
      }
    `,
    variables: {
      language,
      selectedCategory: ""
    },
  });

  let posts = data?.data.posts.edges

    .map(({ node }) => node)
    .map((post) => {
      return {
        ...post,
        language,
        path: `/posts/${post.slug}`,
      };
    });

  const page = {
    ...data?.data.generalSettings,
  };

  return {
    props: {
      page,
      posts,
    },
    revalidate: 5
  };
}